# Generated by Django 5.2.6 on 2025-09-14 05:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('football', 'Football'), ('socks', 'Socks'), ('jersey', 'Jersey'), ('knee guard', 'Knee Guard'), ('shoes', 'Shoes')], default='update', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('product_views', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
