# Generated by Django 5.2.6 on 2025-09-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('football', 'Football'), ('socks', 'Socks'), ('jersey', 'Jersey'), ('knee guard', 'Knee Guard'), ('shoes', 'Shoes')], default='update', max_length=20),
        ),
    ]
